version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  accoon.api:
    image: ${DOCKER_REGISTRY-}accoonapi
    build:
      context: .
      dockerfile: src/Services/AccoonApi/Accoon.Api/Dockerfile
    depends_on:
      - sql.data

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile