version: '3.4'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "2000:80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "2001:1433"  

  accoon.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4000:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro