version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile